query {
  postsQuery{
    count
    results {
      entityUuid
      entityCreated
      entityLabel
      entityUrl {
        alias
      }
      ...on NodePost {
        image
        body
      }
    }
  }
}