# display only promoted articles on homepage
query {
  postsQuery( pageSize:4, contextual_filter:{ promote:"1" } ){
    count
    results {
      created: entityCreated
      title: entityLabel
      url: entityUrl {
        alias
      }
      ...on NodePost {
         image: fieldImage {
            derivative(style:medium) {
              url
            }
         }
         teaser: fieldTeaser
      }
    }
  }
}