query route($path: String!) {
  route(path: $path) {
    alias
    routed
    path
    entity {
      title: entityLabel
      ... on NodePost {
        body: fieldBody
        image: fieldImage {
          derivative(style:large) {
            url
          }
        }
        tags: fieldTags {
          name: entityLabel
          url: entityUrl {
            alias
          }
        }
      }
    }
  }
}