query {
  postsQuery( pageSize:4 ){
    count
    results {
      created: entityCreated
      title: entityLabel
      url: entityUrl {
        alias
      }
      ...on NodePost {
         image: fieldImage
         teaser: fieldTeaser
      }
    }
  }
}